# name: shakemap
# channels:
#   - conda-forge
# dependencies:
#   - python>=3.12,<3.13
#   - pip
#   - rasterio
#   - libgdal-netcdf
#   - gcc
#   - gxx

name: shakemap
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - rasterio
  - libgdal-netcdf
  - gcc
  - gxx
